using DataPrase.Core;
using NUnit.Framework;

namespace DataPrase.Core.Tests
{
    [TestFixture]
    public class DatalogLayoutTests
    {
        private static ICellReader Ets88Sheet()
        {
            // row1=标记；row5=Test Name 行（第 6/7 列有项，第 8 列空）；row16=终止标记
            return new SheetBuilder(30, 10)
                .Set(1, 1, "Report Generated By")
                .Set(5, 1, "Test Name")
                .Set(5, 6, "ItemA")
                .Set(5, 7, "ItemB")
                .Set(16, 1, "Data Collection Start Date")
                .Build();
        }

        [Test]
        public void Ets88_Initial_Calibration()
        {
            var ets = TesterRegistry.Specs[0];
            var layout = DatalogLayout.Compute(ets, 0, Ets88Sheet(), reCalibrate: false);

            Assert.That(layout.TestNameRow, Is.EqualTo(5));
            Assert.That(layout.DataStartColumn, Is.EqualTo(6));
            Assert.That(layout.DataStopColumn, Is.EqualTo(7));
            Assert.That(layout.DataStartRow, Is.EqualTo(11));   // 5 + 6
            Assert.That(layout.DataStopRow, Is.EqualTo(14));    // 16 - 2
            Assert.That(layout.FormulaRow, Is.EqualTo(9));      // 5 + 5 - 1
        }

        [Test]
        public void Ets88_Recalibration_Shifts_DataStart_By_Extra_Seven_Minus_One()
        {
            var ets = TesterRegistry.Specs[0];
            var sheet = new SheetBuilder(30, 10)
                .Set(1, 1, "Report Generated By")
                .Set(5, 1, "Test Name")
                .Set(5, 6, "ItemA")
                .Set(5, 7, "ItemB")
                .Set(24, 1, "Data Collection Start Date")
                .Build();

            var layout = DatalogLayout.Compute(ets, 0, sheet, reCalibrate: true);

            Assert.That(layout.DataStartRow, Is.EqualTo(17));   // 5 + 6 + 7 - 1
            Assert.That(layout.DataStopRow, Is.EqualTo(22));    // 24 - 2
        }

        [Test]
        public void Non_Ets88_Uses_Double_Blank_Row_As_Terminator()
        {
            var cta = TesterRegistry.Specs[1];
            var sheet = new SheetBuilder(20, 20)
                .Set(1, 1, "[GENERAL]")
                .Set(3, 1, "Serial_No")
                .Set(3, 14, "ItemA")
                .Set(3, 15, "ItemB")
                .Column(1, 7, "d", "d", "d", "d")   // rows 7..10 有值，11/12 空
                .Build();

            var layout = DatalogLayout.Compute(cta, 1, sheet, reCalibrate: false);

            Assert.That(layout.TestNameRow, Is.EqualTo(3));
            Assert.That(layout.DataStartColumn, Is.EqualTo(14));
            Assert.That(layout.DataStopColumn, Is.EqualTo(15));
            Assert.That(layout.DataStartRow, Is.EqualTo(7));    // 3 + 4
            Assert.That(layout.DataStopRow, Is.EqualTo(10));    // 12 - 2
            Assert.That(layout.FormulaRow, Is.EqualTo(6));      // 3 + 4 - 1
        }

        [Test]
        public void Column_Scan_Stops_At_First_Blank_Before_DataStop_Column()
        {
            var ets = TesterRegistry.Specs[0];
            var sheet = new SheetBuilder(30, 10)
                .Set(1, 1, "Report Generated By")
                .Set(5, 1, "Test Name")
                .Set(5, 6, "ItemA")
                .Set(5, 8, "ItemC")     // 第 7 列故意留空 → 结束列应停在 6
                .Set(16, 1, "Data Collection Start Date")
                .Build();

            var layout = DatalogLayout.Compute(ets, 0, sheet, reCalibrate: false);

            Assert.That(layout.DataStartColumn, Is.EqualTo(6));
            Assert.That(layout.DataStopColumn, Is.EqualTo(6));
        }

        [Test]
        public void Picks_Widest_Test_Name_Row_When_Narrow_Device_Row_Comes_First()
        {
            var ets = TesterRegistry.Specs[0];
            // 第 4 行设备名行（2 段）在前，第 9 行才是真正的列头（4 段）
            var sheet = new SheetBuilder(30, 10)
                .Set(1, 1, "Report Generated By")
                .Set(4, 1, "Test Name")
                .Set(4, 2, "DeviceName")
                .Set(9, 1, "Test Name")
                .Set(9, 6, "ItemA")
                .Set(9, 7, "ItemB")
                .Set(9, 8, "ItemC")
                .Set(20, 1, "Data Collection Start Date")
                .Build();

            var layout = DatalogLayout.Compute(ets, 0, sheet, reCalibrate: false);

            Assert.That(layout.TestNameRow, Is.EqualTo(9));
            Assert.That(layout.DataStartRow, Is.EqualTo(15));   // 9 + 6
            Assert.That(layout.DataStopColumn, Is.EqualTo(8));
        }

        [Test]
        public void Narrow_Test_Name_Row_After_Wide_One_Does_Not_Override()
        {
            var ets = TesterRegistry.Specs[0];
            // 真列头在 row 5（宽），设备名行在 row 8（窄且在后）——VBA 的「取最后一次匹配」会误选 row 8
            var sheet = new SheetBuilder(30, 10)
                .Set(1, 1, "Report Generated By")
                .Set(5, 1, "Test Name")
                .Set(5, 6, "ItemA")
                .Set(5, 7, "ItemB")
                .Set(5, 8, "ItemC")
                .Set(8, 1, "Test Name")
                .Set(8, 2, "DeviceName")
                .Set(20, 1, "Data Collection Start Date")
                .Build();

            var layout = DatalogLayout.Compute(ets, 0, sheet, reCalibrate: false);

            Assert.That(layout.TestNameRow, Is.EqualTo(5));
            Assert.That(layout.DataStartRow, Is.EqualTo(11));   // 5 + 6
            Assert.That(layout.DataStopColumn, Is.EqualTo(8));
        }
    }
}
