using DataPrase.Core;
using NUnit.Framework;

namespace DataPrase.Core.Tests
{
    [TestFixture]
    public class ProcessPlannerTests
    {
        private static ICellReader Ets88Sheet()
        {
            // 数据行 11..14（第 13 行为空串，应被删）；row16 是终止标记
            return new SheetBuilder(30, 10)
                .Set(1, 1, "Report Generated By")
                .Set(5, 1, "Test Name")
                .Set(5, 6, "ItemA")
                .Set(5, 7, "ItemB")
                .Set(16, 1, "Data Collection Start Date")
                .Column(1, 11, "s", "s", "", "s")
                .Build();
        }

        [Test]
        public void Ets88_Deletes_Empty_Rows_In_Descending_Order()
        {
            var ets = TesterRegistry.Specs[0];
            var sheet = Ets88Sheet();
            var layout = DatalogLayout.Compute(ets, 0, sheet, reCalibrate: false);
            var plan = ProcessPlanner.Build(ets, 0, layout, sheet);

            Assert.That(layout.DataStartRow, Is.EqualTo(11));
            Assert.That(layout.DataStopRow, Is.EqualTo(14));
            Assert.That(plan.EmptyRowsToDelete, Is.EqualTo(new[] { 13 }));
        }

        [Test]
        public void Ets88_Inserts_Six_Rows_And_Adjusts_Data_Range()
        {
            var ets = TesterRegistry.Specs[0];
            var sheet = Ets88Sheet();
            var layout = DatalogLayout.Compute(ets, 0, sheet, reCalibrate: false);
            var plan = ProcessPlanner.Build(ets, 0, layout, sheet);

            Assert.That(plan.InsertRow, Is.EqualTo(10));       // 5 + FormulaRowOffset(5)
            Assert.That(plan.InsertCount, Is.EqualTo(6));
            Assert.That(plan.FormulaTopRow, Is.EqualTo(9));    // 5 + 5 - 1
            Assert.That(plan.DataStartRow, Is.EqualTo(17));    // 11 + 6
            Assert.That(plan.DataStopRow, Is.EqualTo(19));     // 14 + 6 - 1
            Assert.That(plan.HiddenColumns, Is.Empty);
        }

        [Test]
        public void Cta8290D_Inserts_Seven_Rows_And_Hides_Known_Columns()
        {
            var cta = TesterRegistry.Specs[1];
            var sheet = new SheetBuilder(20, 20)
                .Set(1, 1, "[GENERAL]")
                .Set(3, 1, "Serial_No")
                .Set(3, 14, "ItemA")
                .Set(3, 15, "ItemB")
                .Column(1, 7, "d", "d", "d", "d")
                .Build();
            var layout = DatalogLayout.Compute(cta, 1, sheet, reCalibrate: false);
            var plan = ProcessPlanner.Build(cta, 1, layout, sheet);

            Assert.That(plan.InsertRow, Is.EqualTo(7));        // 3 + 4
            Assert.That(plan.InsertCount, Is.EqualTo(7));
            Assert.That(plan.DataStartRow, Is.EqualTo(14));    // 7 + 7
            Assert.That(plan.DataStopRow, Is.EqualTo(17));     // 10 + 7
            Assert.That(plan.HiddenColumns, Is.EqualTo(new[] { 2, 5, 7, 8, 9, 10, 12, 13 }));
            Assert.That(plan.EmptyRowsToDelete, Is.Empty);     // 仅 ETS88 删空行
        }

        [Test]
        public void Sts8200_Inserts_Six_Rows_And_Keeps_All_Columns()
        {
            var sts = TesterRegistry.Specs[3];
            var sheet = new SheetBuilder(20, 20)
                .Set(1, 1, "STS8200-43 StationA")
                .Set(3, 1, "SITE_NUM")
                .Set(3, 9, "ItemA")
                .Set(3, 10, "ItemB")
                .Column(1, 8, "s", "s", "s", "s")
                .Build();
            var layout = DatalogLayout.Compute(sts, 3, sheet, reCalibrate: false);
            var plan = ProcessPlanner.Build(sts, 3, layout, sheet);

            Assert.That(layout.DataStartRow, Is.EqualTo(8));
            Assert.That(layout.DataStopRow, Is.EqualTo(11));
            Assert.That(plan.InsertCount, Is.EqualTo(6));
            Assert.That(plan.DataStartRow, Is.EqualTo(14));
            Assert.That(plan.DataStopRow, Is.EqualTo(17));
            Assert.That(plan.HiddenColumns, Is.Empty);
        }

        [Test]
        public void Stat_Labels_Are_The_Six_Expected()
        {
            var ets = TesterRegistry.Specs[0];
            var sheet = Ets88Sheet();
            var layout = DatalogLayout.Compute(ets, 0, sheet, reCalibrate: false);

            Assert.That(ProcessPlanner.Build(ets, 0, layout, sheet).StatLabels,
                Is.EqualTo(new[] { "Min", "Avg", "Max", "Range", "STD", "CPK" }));
        }
    }
}
