using DataPrase.Core;
using NUnit.Framework;

namespace DataPrase.Core.Tests
{
    [TestFixture]
    public class TesterDetectorTests
    {
        [TestCase("Report Generated By", 0)]
        [TestCase("[GENERAL]", 1)]
        [TestCase("CTA8280F", 2)]
        public void Detects_By_Exact_First_Cell(string firstCell, int expectedIndex)
        {
            var sheet = new SheetBuilder(5, 3).Set(1, 1, firstCell).Build();
            var detection = TesterDetector.Detect(sheet);

            Assert.That(detection.IsDetected, Is.True);
            Assert.That(detection.SpecIndex, Is.EqualTo(expectedIndex));
        }

        [TestCase("STS8200 v1.2.3", 3)]
        [TestCase("[Tester] CTA8280F", 4)]
        public void Detects_By_Substring_First_Cell(string firstCell, int expectedIndex)
        {
            var sheet = new SheetBuilder(5, 3).Set(1, 1, firstCell).Build();
            var detection = TesterDetector.Detect(sheet);

            Assert.That(detection.SpecIndex, Is.EqualTo(expectedIndex));
        }

        [TestCase(2)]
        [TestCase(3)]
        public void Ets88_Fallback_When_Marker_Not_On_Row_1(int markerRow)
        {
            var sheet = new SheetBuilder(5, 3)
                .Set(1, 1, "some preamble")
                .Set(markerRow, 1, "Report Generated By")
                .Build();

            var detection = TesterDetector.Detect(sheet);

            Assert.That(detection.IsDetected, Is.True);
            Assert.That(detection.SpecIndex, Is.EqualTo(0));
        }

        [Test]
        public void Unsupported_When_No_Marker_Matches()
        {
            var sheet = new SheetBuilder(5, 3).Set(1, 1, "totally unknown format").Build();
            var detection = TesterDetector.Detect(sheet);

            Assert.That(detection.IsDetected, Is.False);
            Assert.That(detection.SpecIndex, Is.EqualTo(-1));
            Assert.That(detection.Message, Does.Contain("Unsupported Datalog Type"));
        }

        [Test]
        public void Exact_Match_Wins_Over_Substring_For_Cta8280F()
        {
            // "CTA8280F" 同时满足 spec2 的整格相等与 spec3/4 的子串条件；VBA 先判整格 → 2。
            var sheet = new SheetBuilder(5, 3).Set(1, 1, "CTA8280F").Build();
            Assert.That(TesterDetector.Detect(sheet).SpecIndex, Is.EqualTo(2));
        }
    }
}
