using System.Linq;
using DataPrase.Core;
using NUnit.Framework;

namespace DataPrase.Core.Tests
{
    [TestFixture]
    public class TesterRegistryTests
    {
        [Test]
        public void Specs_Contains_Five_Tester_Configs()
        {
            Assert.That(TesterRegistry.Specs.Count, Is.EqualTo(5));
        }

        [Test]
        public void Specs_Order_Matches_Legacy_Vba()
        {
            var names = TesterRegistry.Specs.Select(s => s.TesterName).ToArray();
            Assert.That(names, Is.EqualTo(new[] { "ETS88", "CTA8290D", "CTA8280F", "STS8200", "CTA8280F" }));
        }

        [Test]
        public void Specs_Identifiers_Match_Legacy_Vba()
        {
            var ids = TesterRegistry.Specs.Select(s => s.DatalogIdentifier).ToArray();
            Assert.That(ids, Is.EqualTo(new[] { "Report Generated By", "[GENERAL]", "CTA8280F", "STS8200", "[Tester]" }));
        }

        [Test]
        public void Substring_Identifier_Flag_Matches_Legacy_Vba_InStr_Usage()
        {
            // VBA 对 STS8200 与 [Tester] 用 InStr 包含匹配，其余三台用整格相等。
            var substringFlags = TesterRegistry.Specs.Select(s => s.IdentifierIsSubstring).ToArray();
            Assert.That(substringFlags, Is.EqualTo(new[] { false, false, false, true, true }));
        }

        [Test]
        public void Ets88_Spec_Preserves_Offsets()
        {
            var ets = TesterRegistry.Specs[0];
            Assert.That(ets.TestItemStartIndex, Is.EqualTo(6));
            Assert.That(ets.TestNameRowIdentifier, Is.EqualTo("Test Name"));
            Assert.That(ets.DataRowOffset, Is.EqualTo(6));
            Assert.That(ets.FormulaRowOffset, Is.EqualTo(5));
            Assert.That(ets.LowOffset, Is.EqualTo(2));
            Assert.That(ets.HighOffset, Is.EqualTo(3));
            Assert.That(ets.UnitOffset, Is.EqualTo(4));
            Assert.That(ets.MinOffset, Is.EqualTo(5));
            Assert.That(ets.MeanOffset, Is.EqualTo(6));
            Assert.That(ets.MaxOffset, Is.EqualTo(7));
            Assert.That(ets.RangeOffset, Is.EqualTo(8));
            Assert.That(ets.StdOffset, Is.EqualTo(9));
            Assert.That(ets.CpkOffset, Is.EqualTo(10));
            Assert.That(ets.BinColumn, Is.EqualTo("$C"));
            Assert.That(ets.SiteColumn, Is.EqualTo("$A"));
        }

        [Test]
        public void Last_Spec_Reverses_Low_High_Offsets_Like_Legacy_Vba()
        {
            // VBA Tester(4)：lowOffset=3、highOffset=2（与其它机型相反），不要"顺手修正"。
            var last = TesterRegistry.Specs[4];
            Assert.That(last.LowOffset, Is.EqualTo(3));
            Assert.That(last.HighOffset, Is.EqualTo(2));
            Assert.That(last.UnitOffset, Is.EqualTo(4));
            Assert.That(last.CpkOffset, Is.EqualTo(10));
            Assert.That(last.BinColumn, Is.EqualTo("$C"));
            Assert.That(last.SiteColumn, Is.EqualTo("$B"));
        }

        [Test]
        public void Sts8200_Spec_Preserves_Offsets()
        {
            var sts = TesterRegistry.Specs[3];
            Assert.That(sts.TestItemStartIndex, Is.EqualTo(9));
            Assert.That(sts.TestNameRowIdentifier, Is.EqualTo("SITE_NUM"));
            Assert.That(sts.DataRowOffset, Is.EqualTo(5));
            Assert.That(sts.FormulaRowOffset, Is.EqualTo(4));
            Assert.That(sts.BinColumn, Is.EqualTo("$D"));
            Assert.That(sts.SiteColumn, Is.EqualTo("$A"));
        }
    }
}
