using DataPrase.Core;
using NUnit.Framework;

namespace DataPrase.Core.Tests
{
    [TestFixture]
    public class VbaStringTests
    {
        [Test]
        public void EqualsPadded_Ignores_Trailing_Spaces_Like_Vba()
        {
            // VBA: "Report Generated By" = "Report Generated By        " → True
            Assert.That(VbaString.EqualsPadded("Report Generated By", "Report Generated By        "), Is.True);
            Assert.That(VbaString.EqualsPadded("Report Generated By        ", "Report Generated By"), Is.True);
        }

        [Test]
        public void EqualsPadded_Is_Case_Sensitive()
        {
            Assert.That(VbaString.EqualsPadded("test name", "Test Name"), Is.False);
        }

        [Test]
        public void EqualsPadded_Rejects_Prefix_With_Trailing_Text()
        {
            Assert.That(VbaString.EqualsPadded("Report Generated By X", "Report Generated By"), Is.False);
        }

        [Test]
        public void EqualsPadded_Numeric_Cell_Matches_String_Literal()
        {
            Assert.That(VbaString.EqualsPadded(1d, "1"), Is.True);
        }

        [Test]
        public void EqualsPadded_Null_Is_Not_Equal()
        {
            Assert.That(VbaString.EqualsPadded(null, "Test Name"), Is.False);
        }

        [Test]
        public void ContainsIgnoreCase_Matches_Substring()
        {
            Assert.That(VbaString.ContainsIgnoreCase("sts8200 rev a", "STS8200"), Is.True);
            Assert.That(VbaString.ContainsIgnoreCase("[GENERAL]", "STS8200"), Is.False);
        }

        [Test]
        public void IsBlank_True_For_Null_But_False_For_Empty_String()
        {
            Assert.That(VbaString.IsBlank(null), Is.True);
            Assert.That(VbaString.IsBlank(string.Empty), Is.False);
        }
    }
}
