# Generated by Django 6.0.5 on 2026-08-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='export_filename_templates',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
