# Generated by Django 6.0.5 on 2026-08-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usersetting_export_filename_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='export_timeout',
            field=models.IntegerField(default=600),
        ),
    ]
