# Generated by Django 6.0.5 on 2026-08-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='chart_renderer',
            field=models.CharField(default='svg', max_length=20),
        ),
    ]
