# Generated by Django 6.0.5 on 2026-08-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usersetting_chart_renderer'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='sftp_last_config',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='sftp_last_host',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='sftp_last_path',
            field=models.CharField(default='/', max_length=1024),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='sftp_last_port',
            field=models.IntegerField(default=22),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='sftp_last_username',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
