# Generated by Django 6.0.5 on 2026-08-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_usersetting_sftp_last_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='default_hidden_columns',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
