# Generated by Django 6.0.5 on 2026-08-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_usersetting_default_hidden_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='sftp_download_timeout',
            field=models.IntegerField(default=600),
        ),
    ]
