# Generated by Django 4.2 on 2026-08-29 新增：文件名自动换行设置（默认开启）

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_usersetting_sftp_download_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='filename_wrap',
            field=models.BooleanField(default=True),
        ),
    ]
