# Generated by Django 6.0.5 on 2026-09-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_usersetting_filename_wrap'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='analysis_chart_memory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='analysis_chart_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
