# Generated by Django 6.0.5 on 2026-09-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_usersetting_analysis_chart_memory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='chart_dpi',
            field=models.IntegerField(default=100),
        ),
    ]
