# Generated by Django 6.0.5 on 2026-05-28 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=512)),
                ('file_size', models.BigIntegerField()),
                ('format_type', models.CharField(choices=[('CTA8290D', 'CTA8290D'), ('CTA8280F', 'CTA8280F'), ('ETS88', 'ETS88'), ('STS8200', 'STS8200')], max_length=20)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('col_count', models.IntegerField(blank=True, null=True)),
                ('program_name', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('parsing', 'Parsing'), ('ready', 'Ready'), ('error', 'Error')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datafiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data File',
                'verbose_name_plural': 'Data Files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('filepath', models.CharField(max_length=512)),
                ('format_type', models.CharField(choices=[('CTA8290D', 'CTA8290D'), ('CTA8280F', 'CTA8280F'), ('ETS88', 'ETS88'), ('STS8200', 'STS8200')], max_length=20)),
                ('rows', models.IntegerField()),
                ('cols', models.IntegerField()),
                ('parsed_at', models.DateTimeField(auto_now_add=True)),
                ('datafile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parse_histories', to='datafiles.datafile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parse_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parse History',
                'verbose_name_plural': 'Parse Histories',
                'ordering': ['-parsed_at'],
            },
        ),
    ]
