# Generated by Django 6.0.5 on 2026-05-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='program_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
