# Generated by Django 6.0.5 on 2026-06-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafiles', '0002_alter_datafile_program_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='batch_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='datafile',
            name='file_type',
            field=models.CharField(choices=[('single', '单文件'), ('batch', '批次文件')], default='single', max_length=10),
        ),
    ]
