# Generated by Django 6.0.5 on 2026-06-07 02:04

from django.db import migrations, models

from apps.datafiles.utils import extract_product_code


def backfill_product_code(apps, schema_editor):
    """Populate product_code for existing rows (derived from filename).

    Safe to backfill because it is deterministic from the filename. We do NOT
    backfill source_mtime — historical files intentionally keep it null.
    """
    DataFile = apps.get_model('datafiles', 'DataFile')
    for df in DataFile.objects.all().iterator():
        code = extract_product_code(df.filename)
        if code and code != df.product_code:
            df.product_code = code
            df.save(update_fields=['product_code'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('datafiles', '0003_add_file_type_batch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='product_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='datafile',
            name='source_mtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_product_code, noop_reverse),
    ]
