# Generated by Django 6.0.5 on 2026-06-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafiles', '0005_datafile_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='sub_batch',
            field=models.CharField(blank=True, default='', help_text='子批次名称（子目录名）', max_length=255),
        ),
    ]
