using System.Collections.Generic;

namespace DataPrase.Core
{
    /// <summary>机台识别结果（对应 VBA 的 g_TesterType）。</summary>
    public sealed class TesterDetection
    {
        private TesterDetection(int specIndex, string message)
        {
            SpecIndex = specIndex;
            Message = message;
        }

        /// <summary>命中的 TesterRegistry 索引；未识别时为 -1。</summary>
        public int SpecIndex { get; private set; }

        public bool IsDetected { get { return SpecIndex >= 0; } }

        public string Message { get; private set; }

        internal static TesterDetection Detected(int specIndex)
        {
            return new TesterDetection(specIndex, null);
        }

        internal static TesterDetection Unsupported(string message)
        {
            return new TesterDetection(-1, message);
        }
    }

    /// <summary>
    /// 机台识别（移植自 VBA DataParser.TestDataRowCalibration 的识别段）。
    /// 顺序敏感：先按整格相等匹配 0/1/2，再按不区分大小写的包含匹配 3/4，
    /// 最后 ETS88 的「首行非 Report Generated By」兜底（查第 2、3 行）。
    /// </summary>
    public static class TesterDetector
    {
        public static TesterDetection Detect(ICellReader sheet)
        {
            IReadOnlyList<TesterSpec> specs = TesterRegistry.Specs;
            object firstCell = sheet.GetValue(1, 1);

            for (int i = 0; i <= 2; i++)
            {
                if (VbaString.EqualsPadded(firstCell, specs[i].DatalogIdentifier))
                {
                    return TesterDetection.Detected(i);
                }
            }

            for (int i = 3; i <= 4; i++)
            {
                if (specs[i].IdentifierIsSubstring
                    && VbaString.ContainsIgnoreCase(firstCell, specs[i].DatalogIdentifier))
                {
                    return TesterDetection.Detected(i);
                }
            }

            // 部分 ETS88 datalog 首行不是 'Report Generated By'，标记出现在第 2 或第 3 行。
            if (VbaString.EqualsPadded(sheet.GetValue(2, 1), specs[0].DatalogIdentifier)
                || VbaString.EqualsPadded(sheet.GetValue(3, 1), specs[0].DatalogIdentifier))
            {
                return TesterDetection.Detected(0);
            }

            return TesterDetection.Unsupported(
                "Unsupported Datalog Type!\r\n" +
                "ETS88: first cell should be 'Report Generated By'\r\n" +
                "CTA8290D: first cell should be '[GENERAL]'\r\n" +
                "CTA8280F: first cell should be 'CTA8280F'");
        }
    }
}
