using System.Collections.Generic;

namespace DataPrase.Core
{
    /// <summary>
    /// 支持的测试机配置（对应 VBA DataParser.Initialize 的 Tester(0..4)）。
    /// 索引顺序与 VBA 一致，识别顺序也依赖该顺序。
    /// </summary>
    public static class TesterRegistry
    {
        private static readonly TesterSpec[] _specs = Build();

        public static IReadOnlyList<TesterSpec> Specs
        {
            get { return _specs; }
        }

        private static TesterSpec[] Build()
        {
            return new[]
            {
                new TesterSpec
                {
                    TesterName = "ETS88",
                    DatalogIdentifier = "Report Generated By",
                    IdentifierIsSubstring = false,
                    TestItemStartIndex = 6,
                    TestNameRowIdentifier = "Test Name",
                    DataRowOffset = 6,
                    FormulaRowOffset = 5,
                    LimitRowOffset = 0,
                    MeanOffset = 6,
                    LowOffset = 2,
                    HighOffset = 3,
                    UnitOffset = 4,
                    MinOffset = 5,
                    MaxOffset = 7,
                    RangeOffset = 8,
                    StdOffset = 9,
                    CpkOffset = 10,
                    BinColumn = "$C",
                    SiteColumn = "$A",
                },
                new TesterSpec
                {
                    TesterName = "CTA8290D",
                    DatalogIdentifier = "[GENERAL]",
                    IdentifierIsSubstring = false,
                    TestItemStartIndex = 14,
                    TestNameRowIdentifier = "Serial_No",
                    DataRowOffset = 4,
                    FormulaRowOffset = 4,
                    LimitRowOffset = 1,
                    MeanOffset = 5,
                    LowOffset = 2,
                    HighOffset = 3,
                    UnitOffset = 1,
                    MinOffset = 4,
                    MaxOffset = 6,
                    RangeOffset = 7,
                    StdOffset = 8,
                    CpkOffset = 9,
                    BinColumn = "$F",
                    SiteColumn = "$D",
                },
                new TesterSpec
                {
                    TesterName = "CTA8280F",
                    DatalogIdentifier = "CTA8280F",
                    IdentifierIsSubstring = false,
                    TestItemStartIndex = 15,
                    TestNameRowIdentifier = "Index_No",
                    DataRowOffset = 4,
                    FormulaRowOffset = 4,
                    LimitRowOffset = 1,
                    MeanOffset = 5,
                    LowOffset = 2,
                    HighOffset = 3,
                    UnitOffset = 1,
                    MinOffset = 4,
                    MaxOffset = 6,
                    RangeOffset = 7,
                    StdOffset = 8,
                    CpkOffset = 9,
                    BinColumn = "$F",
                    SiteColumn = "$D",
                },
                new TesterSpec
                {
                    TesterName = "STS8200",
                    DatalogIdentifier = "STS8200",
                    IdentifierIsSubstring = true,
                    TestItemStartIndex = 9,
                    TestNameRowIdentifier = "SITE_NUM",
                    DataRowOffset = 5,
                    FormulaRowOffset = 4,
                    LimitRowOffset = 1,
                    LowOffset = 2,
                    HighOffset = 3,
                    UnitOffset = 1,
                    MinOffset = 4,
                    MeanOffset = 5,
                    MaxOffset = 6,
                    RangeOffset = 7,
                    StdOffset = 8,
                    CpkOffset = 9,
                    BinColumn = "$D",
                    SiteColumn = "$A",
                },
                new TesterSpec
                {
                    TesterName = "CTA8280F",
                    DatalogIdentifier = "[Tester]",
                    IdentifierIsSubstring = true,
                    TestItemStartIndex = 7,
                    TestNameRowIdentifier = "SERIAL",
                    DataRowOffset = 5,
                    FormulaRowOffset = 5,
                    LimitRowOffset = 1,
                    MeanOffset = 6,
                    LowOffset = 3,
                    HighOffset = 2,
                    UnitOffset = 4,
                    MinOffset = 5,
                    MaxOffset = 7,
                    RangeOffset = 8,
                    StdOffset = 9,
                    CpkOffset = 10,
                    BinColumn = "$C",
                    SiteColumn = "$B",
                },
            };
        }
    }
}
